version: '2'

services:

   squid:
     image: joaniznardo/ubuntum7proxy01
     hostname: squidhost
     container_name: squidcont
     ports:
       - '80:80'
       - '443:443'
     volumes:
       - '/etc/localtime:/etc/localtime:rw'
       - './squid3:/etc/squid3:rw'
     extra_hosts: &llistahosts
       - www.prueba1.com:10.28.1.100
       - www.prueba2.com:10.28.1.100
       - www.prueba3.com:10.28.1.100
       - www.prueba4.com:10.28.1.101
       - www.prueba5.com:10.28.1.101
       - www.prueba6.com:10.28.1.101
     networks:
       x1:
         ipv4_address: 10.28.1.90


   apache1:
     image: joaniznardo/ubuntum7http
     hostname: webserver1
     container_name: webserver1
     volumes:
       - '/etc/localtime:/etc/localtime:rw'
       - './www:/var/www:rw'
       - './sites-available:/etc/apache2/sites-available:rw'
     networks:
       x1:
         ipv4_address: 10.28.1.100

   apache2:
     image: joaniznardo/ubuntum7http
     hostname: webserver2
     container_name: webserver2
     volumes:
       - '/etc/localtime:/etc/localtime:rw'
       - './www:/var/www:rw'
       - './sites-available:/etc/apache2/sites-available:rw'
     networks:
       x1:
         ipv4_address: 10.28.1.101


   client1:
     image: joaniznardo/ubuntum7base
     hostname: client1
     container_name: client1_cont
     domainname: lab42
     extra_hosts: *llistahosts
     networks:
         x1:
           ipv4_address: 10.28.1.102

   client2:
     image: joaniznardo/ubuntum7base
     hostname: client2
     container_name: client2_cont
     domainname: lab42
     extra_hosts: *llistahosts
     networks:
       x1:
         ipv4_address: 10.28.1.103

   client3:
     image: joaniznardo/ubuntum7base
     hostname: client3
     container_name: client3_cont
     domainname: lab42
     extra_hosts: *llistahosts
     networks:
       x1:
         ipv4_address: 10.28.1.104


   firefox:
     image: jlesage/firefox
     hostname: firefox
     container_name: firefox
     environment:
       - FF_PREF_HTTP_PROXY=network.proxy.http=\10.28.1.90:3128\
       - HTTP_PROXY=10.28.1.90:3128
     extra_hosts: *llistahosts
     ports:
       - '5800:5800'
       - '5900:5900'
     volumes:
       - './firefox:/config:rw'
     networks:
       x1:
         ipv4_address: 10.28.1.98

networks:
    x1:
      ipam:
        driver: default
        config:
            - subnet: 10.28.1.0/24
              gateway: 10.28.1.1
              aux_addresses:
                host1: 10.28.1.2
                host2: 10.28.1.3
